### ISSUE TITLE
email lists

### ISSUE THREAD

**Issue by tracykteal** [carpentries/handbook#202]
On the 'Slack and email lists' section, it would be good to add a more full list of the email lists rather than point to the SWC join page.

**Comment by maneesha** [comment]
Now that the Carpentries website is up this should actually point to the [Carpentries page](https://carpentries.org/community/#mailing-lists), rather than the SWC page.

I am reluctant to have the mailing lists spelled out on both the website and the handbook as that means there are two places we have to keep things current.  What do others think?  @ErinBecker @weaverbel

**Comment by maneesha** [comment]
Link to list of mailing lists has been updated with dfdbcd51c78

Do people think we should still have the list of lists in the handbook rather than pointing to the website join page?  @ErinBecker @weaverbel @tracykteal

**Comment by tracykteal** [comment]
I think it's going to be difficult to keep the list of lists synched with the lists in TopicBox, either in the Handbook or on the Join page. Maybe instead we could list the categories of lists, and point to the TopicBox main page for the full list. Categories of lists could be

- local communities
- curriculum 
- discussion
- subcommittees

**Comment by maneesha** [comment]
Right now it links to the Carpentries page with the categorized list of lists.  I agree that it will be difficult to keep the list of lists synced in different places so I'm closing this.
