### ISSUE TITLE
Recommend pre-workshop get-together in host checklist?

### ISSUE THREAD

**Issue by mkcor** [carpentries/handbook#283]
Hi everyone,

If I recall correctly, the operations checklist (at the time https://software-carpentry.org/workshops/operations/) used to recommend (at least, mention) that the host organize a get-together (e.g., dinner) right before the workshop begins, for instructors and organizers to meet in person (and, in spirit, start forming a team).

But I can't find this in https://docs.carpentries.org/topic_folders/hosts_instructors/index.html anymore. Was this recommendation removed intentionally? Or did it fall in the cracks?

Another idea is to couple this pre-workshop in-person get-together with an install party (helping learners with their setup and troubleshooting their issues), as mentioned by @tobyhodges in today's instructor discussion session!

I cherish and value these ice-breaking opportunities; in my experience, they make a tremendous difference in the workshop experience, for everyone involved. So I would like to see them promoted, mentioned (maybe even required<sup>[1]</sup>) _formally_.

Thank you,
Marianne

<a>[1]</a>: For example, if there is "no budget" for coffee and snacks, then maybe we shouldn't organize this workshop, until there _is_ budget for coffee and snacks...?

**Comment by maneesha** [comment]
Hi @mkcor  Thanks for raising this issue here.  We definitely do encourage people to get together before a workshop, as time and budget permits.  As you noted, that's really important as you're going to be working as a team over the next two days.  

We have information for instructors spread out in a couple of places - [Teaching and Hosting](https://docs.carpentries.org/topic_folders/hosts_instructors/index.html)  (which is specifically about teaching at a workshop) and [For Instructors](https://docs.carpentries.org/topic_folders/for_instructors/index.html)  (which includes other resources and ways for instructors to get involved).  I am planning on spending some time reviewing this closely and potentially reorganizing things so it's clearer to find what you're looking for.  

If you have suggestions from the instructor point of view, your feedback would be greatly appreciated!

**Comment by maneesha** [comment]
Hey @mkcor - What do you think of this?  https://github.com/carpentries/handbook/pull/292

**Comment by maneesha** [comment]
Hi @mkcor   I hadn't heard back from you so I merged this PR.  Let me know if you have other suggestions, otherwise I'll close this.

**Comment by mkcor** [comment]
Hi @maneesha ! Sorry for the radio silence; I just took a look and I love this addition. Thank you so much!  Feel free to close this issue.
