### ISSUE TITLE
Should subcommittee info go in the handbook?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#37]
Things like this:
https://github.com/carpentries/mentoring

**Comment by maneesha** [comment]
And this

Information on subcommittees:
List of all committees and links: https://docs.google.com/document/d/1wGSRTVRd7kaSao_6JOrD8A_Oaj39EYre57_Ra5AhEBc/edit#
FAQ’s page: https://docs.google.com/document/d/1ySBX82s0g1yJ7MlpPXsP4WKNP_8CKEpF_pixo5umUB4/edit#
Subcommittee descriptions  https://docs.google.com/document/d/1wGSRTVRd7kaSao_6JOrD8A_Oaj39EYre57_Ra5AhEBc/edit#
Staff Liaison roles https://docs.google.com/document/d/1P5fYNubCFcS21MF_ijpQAe--yS9v_CBEywJ97h7jxHY/edit

**Comment by tobyhodges** [comment]
I think it would be good to include a listing of the various (sub)committees, perhaps with some description of requirements for membership.

**Comment by ErinBecker** [comment]
@maneesha - I'm working on a "Join us" page for the new Carpentries website that overlaps with some of this info. 

Currently being assembled in a Google doc here: https://docs.google.com/document/d/1aLPwbJ5Fb03dHttglZsrCSql5bdzjKeCYl4nxJ6G3fI/edit

It's a bit of a mess at the moment, partially because I'm trying to figure out which of the things that are included should be in the Handbook and which should be on the website. Guidance and comments appreciated.

**Comment by maneesha** [comment]
I like having an overview of each committee ("who we are") on the website's "Join us" section.  That way in one place, on one page, people can see the scope of all Carpentries subgroups.  Each description  can then link to the the handbook where there is detailed information ( "what we do" and "how we do it").

**Comment by maneesha** [comment]
I like the way it is outlined on that google doc - with a paragraph description of the group, with bullets that point to the handbook or other resources.

**Comment by ErinBecker** [comment]
Closing this as this information will go into the Join Us page on the website and will link back to individual Handbook pages where relevant.
