### ISSUE TITLE
Update getting news out section

### ISSUE THREAD

**Issue by kariljordan** [carpentries/handbook#396]
For the [getting news out](https://github.com/carpentries/handbook/blob/master/topic_folders/communications/submit-news-item.md) section of the handbook, do we want to send newsletter content to newsletter@carpentries.org instead of team@?

**Comment by maneesha** [comment]
Whether it goes to team@ or newsletter@carpentries.org, it ultimately reaches us at the same place (via Helpscout).  I'd rather keep one line of communication here, rather than make people feel they have to email different addresses if they want to share the same content.  @kariljordan  If you feel strongly we should have the email addresses differentiated I'd be happy to re-open this issue and discuss this more.
