### ISSUE TITLE
Update section on Spanish translations

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#422]
I'd like to update this section (https://docs.carpentries.org/topic_folders/regional_communities/carpentries_en_latinoamerica.html#traducciones-translations) to read:

The GitHub repos for translations in progress are maintained in the Carpentries-ES organization.

Several Data Carpentry and Software Carpentry lessons have complete Spanish language translations.  These are listed on the [Data Carpentry](https://datacarpentry.org/lessons/) and [Software Carpentry](https://software-carpentry.org/lessons) lesson websites.

Could someone help me with the Spanish translation of this?  You can leave the translation as a comment in this issue and I'll merge into the handbook.  Maybe @raynamharris  @orchid00  anyone else?

**Comment by LUS24** [comment]
1:

The GitHub repos for translations in progress are maintained in the Carpentries-ES organization.

Los respositorios de GitHub para las traducciones en progreso son mantenidos por la organización Carpentries-ES.

2:

Several Data Carpentry and Software Carpentry lessons have complete Spanish language translations. These are listed on the [Data Carpentry](https://datacarpentry.org/lessons/) and [Software Carpentry](https://software-carpentry.org/lessons) lesson websites.

Varias lecciones de Data Carpentry y Software Carpentry tienen traducciones al lenguaje español completas.
Estas se encuentran listadas en los sitios web de las lecciones de [Data Carpentry](https://datacarpentry.org/lessons/) y [Software Carpentry](https://software-carpentry.org/lessons).

I hope it helps

Cheers, Leonardo

**Comment by raynamharris** [comment]
Thanks @LUS24. This is great.  

My only suggestion would be to make both of them a single paragraph, rather than two sentences separated by a blank line. So it would be:

The GitHub repos for translations in progress are maintained in the Carpentries-ES organization. Several Data Carpentry and Software Carpentry lessons have complete Spanish language translations. These are listed on the Data Carpentry and Software Carpentry lesson websites.

and

Los respositorios de GitHub para las traducciones en progreso son mantenidos por la organización Carpentries-ES. Varias lecciones de Data Carpentry y Software Carpentry tienen traducciones al lenguaje español completas.Estas se encuentran listadas en los sitios web de las lecciones de Data Carpentry y Software Carpentry.

**Comment by LUS24** [comment]
Looks good to me.

**Comment by maneesha** [comment]
Fixed with 87942f1c9ff4d2a4b561a7ccda37cb4f89f9782d
Many thanks to @LUS24  and @raynamharris 

Note that the way the handbook is built, it can take up to 24 hours to propagate the changes globally so you may not see this until tomorrow.
