### ISSUE TITLE
Adding information about regional lists to congrats email

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#431]
This is a placeholder issue to make sure I don't forget about the conversation here: https://carpentries.topicbox.com/groups/trainers/T14115799512ec5dc/training-instructors-from-africa

Not sure yet of the best way to add this information to the email template - if there are a lot of regional / local communities, that could get overwhelming in an email. Maybe a pointer to the TopicBox list of groups? Can we filter this list to show specifically only those lists that are for geographically constrained communities? If not, maybe we could have a page or a section in the handbook that lists these groups and point to that?

**Comment by amyehodge** [comment]
We have a local email list at Stanford that is the best mechanism to reach everyone in our group. I'm not sure how this could work. For example, I did online training this week and there just happened to be one person from Stanford at the training. If I hadn't been one of the instructors, I would still love for her to have known about our local email list or for someone to have told me that she was at the training so that I could contact her locally. While I think that seems like the most straightforward thing to do, I understand there may be privacy issues with handing out people's contact info to others. But maintaining an extensive list of all the local groups would be hard. You wouldn't want to try to parse out individual information for 20 different people at a training, but they might not go check a compiled lists somewhere. But that may be the best solution.

**Comment by anenadic** [comment]
Perhaps we can have a dedicated page per country - could for example reuse recently introduced regional pages such as https://carpentries.org/regions_uk/. Regional pages are maintained by the Carpentries but there is a section where we/local admins/coordinators could put extra info - such as information on local groups in the country and their mailing lists for people to join (including country-wide mailing list if it exists). New instructors can then be automatically pointed to the page for their country/region.

**Comment by maneesha** [comment]
We could make a page that links to the [regional coordinators](https://carpentries.org/regionalcoordinators/) page on our website and also includes links to the existing email groups.  [All the ones that start with local- here](https://carpentries.topicbox.com/latest).  I've looked a bit and it does not look like they can be automatically filtered.  

@sheraaronhurt  What do you think of also suggesting they email team on this proposed  page if they want to ask for a list for their region?

**Comment by sheraaronhurt** [comment]
@maneesha that would be good. Where would we put this language for requesting a local region email...on the [RC's](https://carpentries.org/regionalcoordinators/) page? 

@ErinBecker it would be nice to have the pub of the RC's in the congrats email :)

**Comment by maneesha** [comment]
Fixed with 14b4789e5646760ba8e85df3766a220dcb6e4d0f
