### ISSUE TITLE
centrally organized vs. self organized

### ISSUE THREAD

**Issue by sheraaronhurt** [carpentries/handbook#494]
@maneesha the [teaching/hosting](https://github.com/carpentries/handbook/blob/master/topic_folders/hosts_instructors/index.rst) section in the handbook has identical verbiage for Centrally vs. Self organized. 

Also in the handbook there is a scroll box versus the 3 columns like it is seen in the repo.

**Comment by maneesha** [comment]
Thanks for catching this @sheraaronhurt !
What language would you suggest as a quick way to show the difference between the two?

Also in the handbook you see it scrolling because of the template that the handbook is built with.  So tables don't render that great there. We could make this a bulleted list instead of a table to make it easier to read.  What do you think?

**Comment by sheraaronhurt** [comment]
@maneesha  a bulleted list would be preferred. 

Suggested text. Feel free to revise
**Centrally Organized Workshop**
- registration manged by The Carpentries Workshop Administration Team
- instructor recruitment managed by The Carpentries Workshop Administration Team

**Self-Organized Workshop**

- registration managed by local organizer
- instructor recruitment managed by local organizer
