### ISSUE TITLE
Update Assessment Section of Handbook

### ISSUE THREAD

**Issue by kariljordan** [carpentries/handbook#540]
Since we've migrated the learner surveys to Typeform, should we revise the links on the [assessment page](https://github.com/carpentries/handbook/blob/master/topic_folders/assessment/assessment.md)?

**Comment by maneesha** [comment]
Yes, thanks @kariljordan 
I will take care of this.

**Comment by maneesha** [comment]
This page currently has links to the Survey Monkey surveys in preview mode.  Survey Monkey makes it  clear that you're in preview mode when you open those links by giving you a pop up notification.  The title of the page on the browser tab also says "[SURVEY PREVIEW]."

I've been looking at ways to do this in Typeform.  I found [these instructions](https://www.typeform.com/help/sandbox/) but doing this doesn't make the resulting page look any different than the live survey page.  So I'm reluctant to offer this because it may cause mixups between the live page and the preview page.

@fmichonneau  I know you've used Typeform much more than me.  Any suggestions on setting up a preview?  Otherwise we can have a plain text view of the questions so people know what we are asking without going through the survey itself.

**Comment by fmichonneau** [comment]
I've looked a little more into this and I can see 4 options:

1. we use their recommended approach, but I agree with @maneesha that it might cause confusion
1. we create our own link for demonstration purposes: the survey would look exactly the same as it currently does, but after the first screen and before the submission screen, we would display a notice that says that it's not a real workshop survey and invite people to use the links found on the workshop website
1. we embed the surveys within the handbook (like we do for our community calendar for instance) and put a disclaimer on top to make it clear that it's just a preview.
1. we use a text-based approach by either linking to a PDF version of the survey or a plain text.

I like option 3 best because we won't expose the URL to submit the results. What do you think @maneesha and @kariljordan ?

**Comment by maneesha** [comment]
@fmichonneau There is still a "submit" option when you complete an embedded survey, right?  We would want to make sure that those reponses are somehow flagged so that when we do larger reports, those are not included. As long as that works, I'm good with option 3.

Does Typeform let you create a PDF/text of the survey questions?  If so that may be a good option to offer as well.  If we'd have to keep them manually in sync, I don't think that would be good.

**Comment by fmichonneau** [comment]
With the embed option (option 3), we can use the URL they recommend to use for demonstration purposes and thus the answers submitted there wouldn't be included in the results of the surveys.

Not to over-engineer things but an option to provide a PDF/text version would be to use their API to create this document automatically and it could be done as a CRON job to make sure things are up to date.
